### ISSUE TITLE
Tool 1 object disappears after switching tool

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#10]
** Describe the bug **
If you switch your tool from the first to any other, and then switch back, the first tool object (staff) doesn't appear in the player's hands.

** Version **
mainV044

** To Reproduce **
Scroll or use number keys to change tool, then change back to tool 1

** Expected behavior**
The first tool (staff) should appear when switching to it.

** Screenshots **
Pay close attention to the highlighted tool in the bottom right:
![staff start](https://user-images.githubusercontent.com/127724850/236401553-479e736c-9217-46d1-829d-2c887b8a4f65.png)
![staff switched](https://user-images.githubusercontent.com/127724850/236401565-159ac8b2-0c2e-4226-bcdc-12783f8a0c6e.png)
![staff end](https://user-images.githubusercontent.com/127724850/236401574-aed0e033-8a1f-4bfc-83ce-46866699e4ea.png)

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Fixed, issues were due to the input one using an old line of code still so just updated it to use the new version and fixed the bug
