### ISSUE TITLE
Respawn menu doesn't have a respawn button

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#11]
** Describe the bug **
When the player dies, the respawn menu doesn't have a respawn button, just a slider that the user can interact with.

** Version **
mainV044

** To Reproduce **
Die and see the respawn menu.

** Expected behavior**
There should be a button that says "Respawn", instead of a slider.

** Screenshots **
![respawn menu](https://user-images.githubusercontent.com/127724850/236402639-ad802199-1f01-4a3a-9a9f-c203a26958c0.png)

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
The slider is supposed to be a timer to show how long before respawn, just not set up yet, and a temp object for now
