### ISSUE TITLE
Movement jumping glitch

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#12]
** Describe the bug **
After moving from ramps to floors, and sometimes after walking through green walls, player is unable to jump until they transfer to another floor object, such as a ramp or other section of floor.

** Version **
mainV044

** To Reproduce **
Walk through green wall without jumping until all the way through, or walk from ramp to higher floor, then try jumping.

** Expected behavior**
Player should be able to jump at all times

** Screenshots **
![ramp move 1](https://user-images.githubusercontent.com/127724850/236403662-0582bb58-8605-42a6-b21e-987b232bc20c.png)

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Issues with the stay command not working if y velocity wasn't zero should be fixed now,
