### ISSUE TITLE
Tools unuseable after death

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#17]
** Describe the bug **
After you die, you become unable to use the destroy tool and some other tools become a little finicky in their uses on their tasks.

** Version **
v0.1.54-alpha

** To Reproduce **
Die in this build, then try to use tools again.

** Expected behavior**
Tools should work no matter what, unless we want them to not in a specific scenario.

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Due to The Bug with CheckList not working properly, the death was causing these objects to realise this, it was an error message and a bug with the checklist, now fixed this issues with the checklist
