### ISSUE TITLE
Tasks not being interacted with unless at a specific angle

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#18]
** Describe the bug **
Some tasks, mainly the red destroyable rubble, could only be interacted with at a specific angle on one side of the object. The planks that fell from the bridge sometimes couldn't be fixed and could only be pushed by getting under them and pushing them up.

** Version **
v0.1.54-alpha

** To Reproduce **
Attempt to interact with the rubble and yellow tasks from different angles.

** Expected behavior**
Tasks should be able to be interacted with from any angle.

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Some of these issues in testing were due to interaction radius not being properly set

**Comment by Xeleolon** [comment]
Additional extension interactables seem to need to wait for the message to be deleted before working. look into fixing this and check if any other issues

**Comment by Xeleolon** [comment]
Timing issues aren't due to the message but due to timing for how long each interaction can occur is too long need to shorten the time so that we can interact fast. added a center point in the screen which is turned off if we can't interact
