### ISSUE TITLE
UI of Blue tasks appeared way above the object.

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#19]
** Describe the bug **
When using the "refill" tool on the blue refill objects, the bar that shows up that should indicate that it's being refilled slowly appears way above the object

** Version **
v0.1.54-alpha

** To Reproduce **
Go to the objects at the end of the level and use the appropriate tool on them, then look up to see the filling bar a meter or so above the walls

** Expected behavior**
Bar that fills up should just be on the level of the object. Maybe connected to but in front of the centre of the object.

** Screenshots **
![refill bar](https://github.com/Xeleolon/DungeonRestoration_Game/assets/127724850/798e1a88-64ed-4330-a5d0-da4967d669c8)

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Swapped the animation to a alterion of it spawn position by ever the object scale if the offset is set to 0 or an offset
