### ISSUE TITLE
Jump issues while in gas area at the end

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#20]
** Describe the bug **
While the player has the "Gas Killing Player ?" effect, they are able to jump to heights above the pillars. As soon as the "Player recovered" message appears because they moved high enough to get out of the range, they stop jumping up and start to fall until they press space again. Can jump in mid air that way, too. But only in the gas area.

** Version **
v0.1.54-alpha

** To Reproduce **
Hold space anywhere in the gas area, and while mid air in that area too.

** Expected behavior**
Player should only be able to jump once to the same height all around the map, and only while touching ground. Not walls.

** Screenshots **
![jump height](https://github.com/Xeleolon/DungeonRestoration_Game/assets/127724850/d31b5cdb-952e-42f9-887b-84b8252153c8)

** Desktop System **
Windows 10

**Comment by DefinitelyACat** [comment]
It could be argued that with the gas room, the area is filled with magic which allows for higher jumping. Once we have a roof, it won't matter how high you can jump, as long as it's only from the ground and not in the air.

**Comment by Xeleolon** [comment]
issues might be due to the gas border area being a trigger collider will investigate this and look into preventing jumping on walls

**Comment by Xeleolon** [comment]
Should be now fixed with the addition of a requirement of tag for the floor to the jump
