### ISSUE TITLE
Gas trap only kills you once.

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#21]
** Describe the bug **
If you die to the gas trap and respawn, it doesn't affect you a second time, even if you haven't fixed the trap.

** Version **
v0.1.54-alpha

** To Reproduce **
Die to the gas, then respawn and go to the gas area again.

** Expected behavior**
The gas trap should remain active and able to affect and kill the player until it is disabled.

** Screenshots **
N/A

** Desktop System **
Windows 10

** Secondary Note **
Possible thing to consider is that the blue tasks there shouldn't be refillable until the gas trap is disabled, otherwise you'd just be filling the gas that's currently killing you and is currently expelling into the room.

**Comment by Xeleolon** [comment]
the death is interfering with the gas trap, resetting but not restarting properly will investigate

**Comment by Xeleolon** [comment]
Fixed issues with gas not killing player after dying
