### ISSUE TITLE
Main Menu Buttons not working

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#22]
** Describe the bug **
The buttons on the MainMenu scene in Unity don't work as intended. Clicking on any of them doesn't do anything.

** Version **
V1.62

** To Reproduce **
Start the MainMenu scene in Unity and hit play. Then click on the increase/decrease buttons or the LevelOne button. None work.

** Expected behavior**
The Increase/Decrease buttons shout change the level shown in the middle button. The middle button should change the scene to whichever scene was selected.

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Issues seem to be tied to the title border overlaying the level button, stoping the interaction from occurring if it occur again due to new object being added check the order in the layer and the border of those objects in particle text as where the text is can be different from it actual border
