### ISSUE TITLE
Last fixable axe on the ramp disappears when fixed

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#23]
** Describe the bug **
When you attempt to fix the last axe on the ramp, the object entirely disappears instead of repairing to its swinging state. All the other axes are fine.

** Version **
V1.62

** To Reproduce **
Play through the level until you get to the ramps, then use the Repair tool on the last Yellow axe on the ramp.

** Expected behavior**
The axe should revert to its swinging variant.

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Issues due to the axe not having is own axe to repair using the same axe as another axe in the wrong position fixed by creating  a new axe to replace with and assigned to correct position
