### ISSUE TITLE
Pressure Plates keep moving down when object ontop

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#24]
** Describe the bug **
When you stand on the pressure plates, they continue to depress down further and futher. Once they're down and if you don't die, you can't jump or move.

** Version **
mainV1.68

** To Reproduce **
Stand on the pressure plates.

** Expected behavior**
Pressure plates should stop at a certain height/depth, and you should die when they activate.

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by DefinitelyACat** [comment]
This was noticed by Ignius (Riley) and Xeleolon (nathan), but I logged it automatically during in-class testing. They are deserving of the credit for finding this one.

**Comment by Xeleolon** [comment]
Fixed issues by making it check for a rigidbody rather than a tag
