### ISSUE TITLE
Momentum doesn't slow once you jump until you land, not even against walls.

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#25]
** Describe the bug **
When you jump while moving forward, your momentum won't slow to a stop. You'll be able to slowly move up walls or just sit there in mid air, even if you let go of your keyboard.

** Version **
testJumpTestingV1.70

** To Reproduce **
Jump into a wall/pillar while facing it.

** Expected behaviour**
You should hit a wall, then fall down it. Forward momentum should slow to a stop when not touching the keyboard.

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by DefinitelyACat** [comment]
This was noticed by Ignius (Riley), but I logged it automatically during in-class testing. He is deserving of the credit for finding this one.

**Comment by Xeleolon** [comment]
still improving this feature not finished yet,

**Comment by Xeleolon** [comment]
fixed in a small way, issues still persist if you take the object from a forward that is left or right of the true forward this is now fully a bug issues will investigate to remove issues

**Comment by Xeleolon** [comment]
Fixed sticking to wall create a phyic material that make player sliperly so player not sticking to wall additional momentum also reset in direction of collision properly
