### ISSUE TITLE
Task list not updating for some of the tasks

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#26]
** Describe the bug **
When you disable the gas, it doesn't check off of the tasklist. Possibilities of other tasks behaving similarly.

** Version **
mainV1.68

** To Reproduce **
Speedrun to the gas chamber and hit the button to turn it off, then check the tasklist.

** Expected behavior**
Any tasks completed should be checked off or updated on the tasklist.

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
issues was due to Completed function needing to be called in the toggle on/off script if issues occurs on another object with a different interacted get coders to check if completed() is being called by that script first.
