### ISSUE TITLE
Camera too floaty after controls were changed between mouse and controller

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#34]
** Describe the bug **
Camera continues on after a movement of the mouse. If the mouse is moved quickly left to right, the camera seems to fight back and only moves the first direction

** Version **
mainV1.79

** To Reproduce **
Move camera back and forth while playing in the scene

** Expected behaviour**
Camera should stop when the mouse stops moving. Camera should also be responsive on quick turns back and forth, matching how the player moves the mouse.

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Possibly issues due to new controls will investigate before the final submission

**Comment by Xeleolon** [comment]
played around with the setting and data should be nearly fixed just need team to give input on they preferred standards

**Comment by Xeleolon** [comment]
issues have been fixed currently setting the camera acceleration to 6500 and sensitivity to 10
