### ISSUE TITLE
Broken Axes Aren't Being Replaced by Functioning Axes

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#37]
** Describe the bug **
Currently, the final door can be opened before gas is disarmed

** Version **
mainV1.98

** To Reproduce **
Try to fix the yellow axes

** Expected behavior**
The yellow axes should fix and turn into the swinging, functioning axes

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Fixed
