### ISSUE TITLE
First Functioning Axe in the Hallway Doesn't Kill the Player

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#38]
** Describe the bug **
The first axe in the hallway that is already swinging doesn't affect the player. Doesn't push or kill them.

** Version **
mainV1.98

** To Reproduce **
Get in the way of the first axe

** Expected behavior**
All functioning axes should kill the player on contact

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
replaced with a working one
