### ISSUE TITLE
Pillars in Final Room of Updated Level Have No Colliders

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#39]
** Describe the bug **
As in title, the pillars, gem and gem plinth have no colliders and the player can run through them.

** Version **
mainV1.98

** To Reproduce **
Get to end room and run through the previously mentioned objects

** Expected behavior**
Objects should stop player from walking through

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
colliders added
