### ISSUE TITLE
Pause Menu Rotation

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#6]
** Describe the bug **
When hitting Esc to open the pause menu, the character slowly rotates on the spot. Sometimes it's clockwise, sometimes couter-clockwise.

** Version **
mainV044

** To Reproduce **
Hit the 'Esc' Key on the keyboard when playing the game.

** Expected behavior**
Stationary view when opening pause menu.

** Screenshots **
NA

** Desktop System **
Windows 10

**Comment by DefinitelyACat** [comment]
So I've retested and found out that this only occurs when you have touched any object in the level that can move. Walls, pillars and the Gem Plinth don't count. Once you've touched one of the moveable boxes or objects, you rotate when paused.
Another thing is that if you pause while moving, you continue to move. If you've touched a moveable object, you continue to move and rotate while paused. It's almost as though it keeps using your last input command while paused.
As soon as you unpause, your rotation goes back to the original way you were facing when you paused, even if you moved position.

**Comment by Xeleolon** [comment]
fixed issues the rotation was due to the player moving camera just before enter menu, and the motion continue through with no force reset, now fixed so motion won't keep rotating
