### ISSUE TITLE
Tool movement out of sync

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#7]
** Describe the bug **
When moving the camera left and right, the held tools stay with the camera as though in the player's hands. When moving the camera up and down, the tools move up and down, almost seeming to warp their object perspectives.

** Version **
mainV044

** To Reproduce **
Move mouse up or down to shift player's view while in game.

** Expected behavior**
Tools should move with the camera the same way up and down as they do left and right.

** Screenshots **
![tool normal](https://user-images.githubusercontent.com/127724850/236394333-1a05d242-17a5-43c2-8145-88827969e23b.png)
![Tool up](https://user-images.githubusercontent.com/127724850/236394344-10e981ff-51c5-4cb4-8334-2cac53c59190.png)

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Issues with Rotation messing with object scale, need to look into finding a fux

**Comment by Xeleolon** [comment]
This can be fixed by ensuring the object on the top scale is a square overwise distortion will occur have now fixed
