### ISSUE TITLE
Starting Bridge doesn't come back after respawn

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#8]
** Describe the bug **
If all the boards disappear, they don't come back after you respawn and you can't jump the gap that's left in the bridge. You have to restart the level in order to get through.

** Version **
mainV044

** To Reproduce **
Walk onto all of the bridge's disappearing boards, then die before reaching the checkpoint and respawn at the start.

** Expected behavior**
Bridge boards should respawn when the player does.

** Screenshots **
![start bridge](https://user-images.githubusercontent.com/127724850/236399113-b91fccb8-7834-4d46-a55e-f9c3b033d1ce.png)
![empty bridge](https://user-images.githubusercontent.com/127724850/236399124-11e64d0b-9314-465f-972f-fbfb7c7246af.png)

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Added Fix bridge to broken bridge that spawns when bridges disappear so need to fix the bridge to get across
