### ISSUE TITLE
Out of place Ramp in the sky

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/DungeonRestoration_Game#9]
** Describe the issue**
Just a random object in the sky

** Version **
mainV044

** To Reproduce **
look up

** Expected behavior**
Object should not be there

** Screenshots **
![ramp](https://user-images.githubusercontent.com/127724850/236399596-d3fd22a6-df4a-40eb-aca5-c4aa3dd762ea.png)

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Removed
